elasticsearch:
    build: elasticsearch
    user: oneweb
    ports:
        - 9200:9200
    volumes:
        - ./data/elasticsearch:/opt/oneweb/elasticsearch/data
        - ./log/elasticsearch:/opt/oneweb/elasticsearch/log

logstash:
    build: logstash
    user: oneweb
    ports:
        - 5044:5044
    links:
        - elasticsearch

kibana:
    build: kibana
    user: oneweb
    ports:
        - 5601:5601
    links:
        - elasticsearch

filebeat:
    build: filebeat
    user: oneweb
    volumes:
        - ./log/services:/opt/oneweb/services
    links:
        - logstash

oneweb-sdk:
    build: oneweb-sdk
    user: oneweb
    ports:
        - 8080:8080
    volumes:
        - ./log/services/oneweb-sdk:/opt/oneweb/oneweb-sdk/logs