elasticsearch:
    build: ./elasticsearch
    user: oneweb
    ports:
        - 9200:9200
    volumes:
        - ./data/elasticsearch:/opt/oneweb/elasticsearch/data
        - ./log/elasticsearch:/opt/oneweb/elasticsearch/log