filebeat:
    prospectors:
        - 
            paths:
                - '/opt/oneweb/services/oneweb-sdk/*.log'
            input_type: log
            document_type: logs
            fields:
                tenant: core
                appliance: core-d01
                service: core-d01-tomcat-sdk-1
                service_impl: proxy
                shipper: filebeat
                tags: 'filebeat,core-d01-tomcat-sdk-1,tomcat'
    registry_file: /opt/oneweb/fb_registry.filebeat
shipper:
    name: core-d01-fb-1
output:
    logstash:
        hosts:
            - 'logstash:5044'
        worker: 1
        index: catalina
logging:
    to_syslog: false
    to_files: true
    files:
        path: /opt/oneweb/services/filebeat
        name: filebeat.log
        rotateeverybytes: 10485760
        keepfiles: 5
        level: info
