filebeat:
    prospectors:
        -
            paths:
                - /opt/oneweb/services/oneweb-sdk/*.log
            input_type: catalina
            document_type: catalina
            
        -
            paths:
                - /var/log/syslog
            input_type: syslog
            document_type: linux

registry_file: /opt/oneweb/fb_registry.filebeat

output:
    logstash:
        hosts: ["logstash:5044"]
        worker: 1